"""empty message

Revision ID: 472610b12671
Revises: bd84cbf9c9c8
Create Date: 2019-04-25 13:58:01.296378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472610b12671'
down_revision = 'bd84cbf9c9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('end_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
